/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package compiler;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MULT = 6;
  /** RegularExpression Id. */
  int NUM = 7;
  /** RegularExpression Id. */
  int DIGIT = 8;
  /** RegularExpression Id. */
  int LP = 9;
  /** RegularExpression Id. */
  int RP = 10;
  /** RegularExpression Id. */
  int ASSIGN = 11;
  /** RegularExpression Id. */
  int RARROW = 12;
  /** RegularExpression Id. */
  int LARROW = 13;
  /** RegularExpression Id. */
  int SEMI = 14;
  /** RegularExpression Id. */
  int COLON = 15;
  /** RegularExpression Id. */
  int IF = 16;
  /** RegularExpression Id. */
  int ELSE = 17;
  /** RegularExpression Id. */
  int END = 18;
  /** RegularExpression Id. */
  int WHILE = 19;
  /** RegularExpression Id. */
  int FOR = 20;
  /** RegularExpression Id. */
  int CMP = 21;
  /** RegularExpression Id. */
  int DEF = 22;
  /** RegularExpression Id. */
  int TYPE = 23;
  /** RegularExpression Id. */
  int FUNC = 24;
  /** RegularExpression Id. */
  int ID = 25;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "<PLUS>",
    "<MULT>",
    "<NUM>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "<ASSIGN>",
    "\"->\"",
    "\"<-\"",
    "\";\"",
    "\":\"",
    "\"?\"",
    "\"??\"",
    "\"!\"",
    "\"@\"",
    "\"&\"",
    "<CMP>",
    "\"def\"",
    "<TYPE>",
    "\"func\"",
    "<ID>",
    "\",\"",
  };

}
